doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # configure these for your database server
                url: '%env(resolve:DATABASE_URL)%'
#                driver: 'pdo_mysql'
#                server_version: '5.7'
#                charset: utf8mb4
            dbsuivi:
                url: '%env(resolve:DATABASE_SUIVI_URL)%'
                # configure these for your database server
#                driver: 'pdo_mysql'
#                server_version: '5.7'
#                charset: utf8mb4
    orm:

        default_entity_manager: default
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: default
                mappings:
                    App:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Main'
                        prefix: 'App\Entity\Main'
                        alias: App
                dql:
                    datetime_functions:
                        DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat
                        DAY: DoctrineExtensions\Query\Mysql\Day
                        MONTH: DoctrineExtensions\Query\Mysql\Month
                        YEAR: DoctrineExtensions\Query\Mysql\Year

            dbsuivi:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: dbsuivi
                mappings:
                    Suivi:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Suivi'
                        prefix: 'App\Entity\Suivi'
                        alias: Suivi

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
