# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
#        handler_id: null
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        name: cookieYouUp
        cookie_lifetime: 86400
        cookie_httponly: false
#        cookie_secure: true
#        cookie_samesite: none
        use_cookies: true
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true
#    error_controller: App\Controller\ErrorController::show

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error